//
//  SearchViewController.swift
//  Covid Tracer
//
//  Created by Leo Leljak on 23/10/2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

final class SearchViewController: UIViewController {

    // MARK: - IBOutlet -
    @IBOutlet weak var searchTextField: UITextField!
    
    // MARK: - Public properties -

    var presenter: SearchPresenterInterface!

    // MARK: - Private properties -

    private let disposeBag = DisposeBag()

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        setupView()
    }

}

// MARK: - Extensions -

extension SearchViewController: SearchViewInterface {
}

private extension SearchViewController {

    func setupView() {
        
        
        let output = Search.ViewOutput(searchText: searchTextField.rx.text.asDriver())
        
        let input = presenter.configure(with: output)
    }

}
