//
//  SearchPresenter.swift
//  Covid Tracer
//
//  Created by Leo Leljak on 23/10/2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import RxSwift
import RxCocoa

final class SearchPresenter {

    // MARK: - Private properties -

    private unowned let view: SearchViewInterface
    private let interactor: SearchInteractorInterface
    private let wireframe: SearchWireframeInterface
    private let disposeBag = DisposeBag()
    
    private let searchRelay: BehaviorRelay<String?>
    
    // MARK: - Lifecycle -

    init(view: SearchViewInterface, interactor: SearchInteractorInterface, wireframe: SearchWireframeInterface, relay: BehaviorRelay<String?>) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
        self.searchRelay = relay
    }
}

// MARK: - Extensions -

extension SearchPresenter: SearchPresenterInterface {

    func configure(with output: Search.ViewOutput) -> Search.ViewInput {
        
        output
            .searchText
            .debounce(.milliseconds(300))
            .drive(searchRelay)
            .disposed(by: disposeBag)
        
        return Search.ViewInput()
    }

}
