# Uncomment the next line to define a global platform for your project
 platform :ios, '14.0'

target 'Covid Tracer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Covid Tracer
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Alamofire'
  pod 'CodableAlamofire'

end
