//
//  HomePresenter.swift
//  Covid Tracer
//
//  Created by Leo Leljak on 23/10/2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import RxSwift
import RxCocoa

final class HomePresenter {

    // MARK: - Private properties -

    private unowned let view: HomeViewInterface
    private let interactor: HomeInteractorInterface
    private let wireframe: HomeWireframeInterface
    
    private let disposeBag = DisposeBag()

    private let searchedCountry = BehaviorRelay<String?>(value: "Croatia")
    
    // MARK: - Lifecycle -

    init(view: HomeViewInterface, interactor: HomeInteractorInterface, wireframe: HomeWireframeInterface) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension HomePresenter: HomePresenterInterface {

    func configure(with output: Home.ViewOutput) -> Home.ViewInput {
        
        
        handleSearchButtonTap(for: output.searchHandler)
        
        let covidCases = searchedCountry
            .flatMapLatest { [unowned self] in
                self.interactor.getCovidData(for: $0!).asDriver(onErrorDriveWith: .never())
            }
        
        let formattedHeader = formatHeaderData(with: covidCases.asDriver(onErrorDriveWith: .never()))
        let cellItems = getStatisticCellItems(with: covidCases.asDriver(onErrorDriveWith: .never()))
        
        return Home.ViewInput(headerData: formattedHeader, cellItems: cellItems, currentCountry: searchedCountry.asDriver())
    }
}


private extension HomePresenter {
    
    func handleSearchButtonTap(for button: Signal<Void>) {
        button
            .emit { _ in
                self.wireframe.navigate(to: .search(relay: self.searchedCountry))
            }
            .disposed(by: disposeBag)
    }
    
    func formatHeaderData(with cases: Driver<[CovidData]>) -> Driver<HeaderData> {
        let dummyHeaderData = HeaderData.init(activeCases: "n/a", deathCases: "n/a", newCases: "n/a")
        
        return cases.map { cases -> HeaderData in
            guard let lastCase = cases.last else { return dummyHeaderData }
            let yesterdayCase = cases[cases.count - 2]
            
            let activeCases = "\(lastCase.active)"
            let confirmed = "\(lastCase.confirmed - yesterdayCase.confirmed)"
            let deathCases = "\(lastCase.deaths - yesterdayCase.deaths)"
            
            return HeaderData(activeCases: activeCases, deathCases: deathCases, newCases: confirmed)
        }.asDriver()
    }
    
    func getStatisticCellItems(with cases: Driver<[CovidData]>) -> Driver<[StatisticTableCellItem]> {
        
        cases
            .map { covidData -> [StatisticTableCellItem] in
                var cellItems: [StatisticTableCellItem] = []
                
                StatisticCellType.allCases.forEach { cellItems.append(StatisticTableCellItem(model: covidData, cellType: $0)) }
                return cellItems
            }.asDriver()
        
    }
    
}

