//
//  HomeInterfaces.swift
//  Covid Tracer
//
//  Created by Leo Leljak on 23/10/2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

enum HomeNavigationOption {
    case search(relay: BehaviorRelay<String?>)
}

protocol HomeWireframeInterface: WireframeInterface {
    func navigate(to screen: HomeNavigationOption)
}

protocol HomeViewInterface: ViewInterface {
}

protocol HomePresenterInterface: PresenterInterface {
    func configure(with output: Home.ViewOutput) -> Home.ViewInput
}

protocol HomeInteractorInterface: InteractorInterface {
    func getCovidData(for country: String) -> Single<[CovidData]>
}

enum Home {

    struct ViewOutput {
        let searchHandler: Signal<Void>
    }

    struct ViewInput {
        let headerData: Driver<HeaderData>
        let cellItems: Driver<[StatisticTableCellItem]>
        let currentCountry: Driver<String?>
    }

}
